name: Build

on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash build.sh
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/