name: Build

on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom build.sh
        run: bash build.sh

      - if: ${{ inputs.upload-pages-artifact }}
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
     
      - name: List artifacts
        run: |
          echo "Listing artifacts:"
          ls -lR .