name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run GraphVisualizer build
        run: bash .github/gv-build.sh

      - name: List GraphVisualizer build
        run: |
          echo "Listing artifacts:"
          find ./.gv-build

      - name: Create and upload GraphVisualizer artifact
        uses: actions/upload-artifact@v4
        with:
          name: gv-artifact
          path: ./.gv-build/
    
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: gv-artifact
          path: ./.gv-build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: List artifacts
        run: |
          echo "Listing artifacts:"
          find .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: gv-artifact
