name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload-pages-artifact: true

  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}