name: gv-build-deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  gv-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gv-Build
        run: bash .github/gv-build.sh

      - name: List gv-Build
        run: find ./.gv-build

      - name: Create and upload gv-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gv-artifact
          path: ./.gv-build/
          if-no-files-found: error
          include-hidden-files: true
    
  gv-deployment:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: gv-build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download gv-Artifact
        uses: actions/download-artifact@v4
        with:
          name: gv-artifact
          path: ./.gv-build

      - name: List downloaded gv-Artifact
        run: find ./.gv-build

      - name: Deploy gv-Pages
        uses: actions/deploy-pages@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: gv-artifact
